# Generated by Django 5.2.15 on 2026-06-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='category',
            field=models.CharField(choices=[('school', 'School Managemnet'), ('restaurant', 'Restaurant Management'), ('Library', 'Library Managemnet')], default='school', max_length=20),
        ),
    ]
