# Generated by Django 5.2.15 on 2026-08-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='category',
        ),
    ]
