# Generated by Django 5.2.15 on 2026-08-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('chef', 'Chef')], default='owner', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.branch'),
        ),
    ]
