# Generated by Django 5.2.15 on 2026-07-02 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bs_year', models.PositiveIntegerField()),
                ('bs_month', models.PositiveSmallIntegerField(help_text='1 = Baisakh ... 12 = Chaitra')),
                ('bs_day', models.PositiveSmallIntegerField()),
                ('ad_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, help_text='Romanized / English name', max_length=200)),
                ('title_np', models.CharField(blank=True, help_text='Nepali (Devanagari) name', max_length=200)),
                ('tithi', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('holiday', 'Public Holiday'), ('festival', 'Festival'), ('event', 'Event')], default='event', max_length=20)),
                ('is_holiday', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('seed', 'Seeded dataset'), ('tenant', 'Tenant-created')], default='tenant', max_length=20)),
            ],
            options={
                'ordering': ['bs_year', 'bs_month', 'bs_day'],
                'indexes': [models.Index(fields=['bs_year', 'bs_month'], name='calendars_c_bs_year_437817_idx')],
                'constraints': [models.UniqueConstraint(fields=('bs_year', 'bs_month', 'bs_day', 'title_np', 'source'), name='uniq_calendar_event_per_day')],
            },
        ),
    ]
